name: spot-quality

on:
  push:
  pull_request:

jobs:
  typos-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crate-ci/typos@master
        with:
          config: ./.github/workflows/typos.toml

  ci-check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          default: true
          components: rustfmt

      - name: Add empty config.rs
        run: |
          echo >> src/config.rs

      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  shell-check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt-get -y update && sudo apt-get -y install shellcheck
          find $GITHUB_WORKSPACE -type f -and \( -name "*.sh" \) | xargs shellcheck
